# Generated by Django 3.2.3 on 2021-05-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campo1', models.CharField(max_length=20)),
                ('campo2', models.IntegerField(default=20)),
                ('campo3', models.CharField(max_length=20)),
                ('campo4', models.CharField(max_length=20)),
                ('campo5', models.EmailField(max_length=40)),
                ('campo6', models.BooleanField()),
                ('campo7', models.CharField(max_length=20)),
                ('campo8', models.CharField(max_length=20)),
                ('campo9', models.CharField(max_length=20)),
                ('campo10', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p1', models.CharField(max_length=10)),
                ('p2', models.BooleanField()),
                ('p3', models.DateField()),
                ('p4', models.TimeField()),
                ('p5', models.FloatField()),
                ('p6', models.TextField()),
                ('p7', models.CharField(max_length=40)),
                ('p8', models.CharField(max_length=40)),
                ('p9', models.CharField(max_length=40)),
                ('p10', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('sinopse', models.CharField(max_length=500)),
                ('imagem', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='tec_noticias.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=500)),
                ('data', models.DateField()),
                ('ntc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Noticia', to='tec_noticias.noticia')),
            ],
        ),
    ]
