# Generated by Django 3.2.3 on 2021-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
