# Generated by Django 3.2.3 on 2021-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0002_auto_20210518_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=40)),
                ('p2', models.CharField(max_length=10)),
                ('p3', models.CharField(max_length=40)),
                ('p4', models.CharField(max_length=40)),
                ('p5', models.CharField(max_length=40)),
                ('p6', models.CharField(max_length=40)),
                ('p7', models.CharField(max_length=40)),
                ('p8', models.CharField(max_length=40)),
                ('p9', models.CharField(max_length=40)),
                ('p10', models.CharField(max_length=40)),
            ],
        ),
    ]
