# Generated by Django 3.2.3 on 2021-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0003_quizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='p1',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='p2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='p3',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='p4',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='p5',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='p6',
            field=models.TextField(),
        ),
    ]
