# Generated by Django 3.2.3 on 2021-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0005_alter_quizz_p1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
