# Generated by Django 3.2.3 on 2021-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0007_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='campo1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='campo3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='campo4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='campo7',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='campo8',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='campo9',
            field=models.CharField(max_length=20),
        ),
    ]
