# Generated by Django 3.2.3 on 2021-05-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0008_auto_20210523_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('sinopse', models.CharField(max_length=10)),
                ('imagem', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=400)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='tec_noticias.categoria')),
            ],
        ),
    ]
