# Generated by Django 3.2.3 on 2021-05-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0009_categoria_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sinopse',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
