# Generated by Django 3.2.3 on 2021-05-24 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0011_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
