# Generated by Django 3.2.3 on 2021-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0012_categoria_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.CharField(max_length=100),
        ),
    ]
