# Generated by Django 3.2.3 on 2021-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0013_auto_20210524_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='sinopse',
            field=models.CharField(max_length=200),
        ),
    ]
