# Generated by Django 3.2.3 on 2021-05-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0014_alter_noticia_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='sinopse',
            field=models.CharField(max_length=500),
        ),
    ]
