# Generated by Django 3.2.3 on 2021-05-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0015_alter_noticia_sinopse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario_Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=500)),
                ('data', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='Comentarios_Noticias', to='tec_noticias.Comentario_Noticia'),
        ),
    ]
