# Generated by Django 3.2.3 on 2021-05-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0017_remove_noticia_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario_Noticia',
        ),
    ]
