# Generated by Django 3.2.3 on 2021-05-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tec_noticias', '0018_delete_comentario_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario_Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=500)),
                ('data', models.DateField()),
                ('ntc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticia', to='tec_noticias.noticia')),
            ],
        ),
    ]
